#include <stdio.h>
#include <stddef.h>
#include "msquic.h"
#define P(s,f) printf(#s "." #f " = %zu\n", offsetof(s,f))
int main(){
 printf("sizeof QUIC_STATUS=%zu HQUIC=%zu\n", sizeof(QUIC_STATUS), sizeof(HQUIC));
 printf("sizeof QUIC_SETTINGS=%zu\n", sizeof(QUIC_SETTINGS));
 P(QUIC_SETTINGS,PeerBidiStreamCount); P(QUIC_SETTINGS,PeerUnidiStreamCount); P(QUIC_SETTINGS,MaxOperationsPerDrain); P(QUIC_SETTINGS,IdleTimeoutMs); P(QUIC_SETTINGS,KeepAliveIntervalMs);
 printf("sizeof QUIC_REGISTRATION_CONFIG=%zu QUIC_CREDENTIAL_CONFIG=%zu QUIC_BUFFER=%zu\n", sizeof(QUIC_REGISTRATION_CONFIG), sizeof(QUIC_CREDENTIAL_CONFIG), sizeof(QUIC_BUFFER));
 P(QUIC_CREDENTIAL_CONFIG,Flags); P(QUIC_CREDENTIAL_CONFIG,Principal); P(QUIC_CREDENTIAL_CONFIG,AllowedCipherSuites); P(QUIC_CREDENTIAL_CONFIG,CaCertificateFile);
 printf("sizeof QUIC_CONNECTION_EVENT=%zu QUIC_STREAM_EVENT=%zu\n", sizeof(QUIC_CONNECTION_EVENT), sizeof(QUIC_STREAM_EVENT));
 P(QUIC_CONNECTION_EVENT,PEER_STREAM_STARTED.Stream); P(QUIC_CONNECTION_EVENT,PEER_STREAM_STARTED.Flags);
 P(QUIC_CONNECTION_EVENT,DATAGRAM_RECEIVED.Buffer); P(QUIC_CONNECTION_EVENT,DATAGRAM_RECEIVED.Flags);
 P(QUIC_CONNECTION_EVENT,SHUTDOWN_INITIATED_BY_TRANSPORT.Status); P(QUIC_CONNECTION_EVENT,SHUTDOWN_INITIATED_BY_TRANSPORT.ErrorCode);
 P(QUIC_CONNECTION_EVENT,SHUTDOWN_INITIATED_BY_PEER.ErrorCode);
 P(QUIC_CONNECTION_EVENT,DATAGRAM_STATE_CHANGED.SendEnabled); P(QUIC_CONNECTION_EVENT,DATAGRAM_STATE_CHANGED.MaxSendLength);
 P(QUIC_STREAM_EVENT,START_COMPLETE.Status); P(QUIC_STREAM_EVENT,START_COMPLETE.ID);
 P(QUIC_STREAM_EVENT,RECEIVE.AbsoluteOffset); P(QUIC_STREAM_EVENT,RECEIVE.TotalBufferLength); P(QUIC_STREAM_EVENT,RECEIVE.Buffers); P(QUIC_STREAM_EVENT,RECEIVE.BufferCount); P(QUIC_STREAM_EVENT,RECEIVE.Flags);
 P(QUIC_STREAM_EVENT,PEER_SEND_ABORTED.ErrorCode);
 P(QUIC_STREAM_EVENT,SEND_COMPLETE.ClientContext);
 printf("QUIC_EXECUTION_PROFILE_LOW_LATENCY=%d QUIC_CREDENTIAL_TYPE_NONE=%d QUIC_ADDRESS_FAMILY_UNSPEC=%d QUIC_STATUS_PENDING=%u\n", QUIC_EXECUTION_PROFILE_LOW_LATENCY, QUIC_CREDENTIAL_TYPE_NONE, QUIC_ADDRESS_FAMILY_UNSPEC, (unsigned)QUIC_STATUS_PENDING);
 printf("STREAM_ID param=0x%x\n", QUIC_PARAM_STREAM_ID);
 return 0; }
